from board import *

class PlayerLvl1:
    def __init__(self) -> None: ...
    def __isCycle(self, node: Node) -> bool: ...

    def BFS(self, board: Board) -> dict[str, list[set[int, int]]]: ...
    def DFS(self, board: Board) -> dict[str, list[set[int, int]]]: ...
    def UCS(self, board: Board) -> dict[str, list[set[int, int]]]: ...
    def GBFS(self, board: Board) -> dict[str, list[set[int, int]]]: ...
    def AStar(self, board: Board) -> dict[str, list[set[int, int]]]: ...

class PlayerLvl2:
    def __init__(self, timeAllowed: int) -> None: ...
    def __get_children(self, board: Board, node: Node) -> list[Node]: ...
    def __recursive_DLS(self, board: Board, node: Node, limit: int) -> Node | int: ...

    def move(self, board: Board) -> dict[str, list[set[int, int]]]: ...

class PlayerLvl3:
    def __init__(self, timeAllowed: int, fuelCapacity: int) -> None: ...
    def __get_children(self, board: Board, node: Node) -> list[Node]: ...
    def __recursive_DLS(self, board: Board, node: Node, limit: int, goal: set[int, int]) -> Node | int: ...
    def __IDS(self, board: Board, goal: set[int, int]) -> Node | int: ...

    def move(self, board: Board) -> dict[str, list[set[int, int]]]: ...

class PlayerLvl4:
    def __init__(self, timeAllowed: int, fuelCapacity: int) -> None: ...
    def __get_children(self, board: Board, node: Node) -> list[Node]: ...
    def __get_next_location_hill_climbing(self, board: Board, node: Node, goal: set[int, int]) -> Node: ...
    def __multiagents_hill_climbing(self, board: Board) -> dict[str, list[set[int, int]]]: ...

    def move(self, board: Board) -> dict[str, list[set[int, int]]]: ...